name: "SWD Deployment final"

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "npm"
                  cache-dependency-path: package-lock.json
            - name: Install dependencies
              run: npm install
            - name: Build file
              run: npm run build

            - name: Deploy production to Netlify
              uses: South-Paw/action-netlify-deploy@v1.2.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
                  build-dir: "./build"
                  comment-on-commit: false
IMPORTANT!
DO NOT COPY THIS OVER YET! First, we will breakdown what the file is doing for you!

Let's start on the first few lines:

name: "SWD Deployment 1"

on:
    push:
        branches:
            - main
name is exactly that, this just names the project that we're using this workflow file for.

on: represents any actions we want to watch for that occur on the repository itself, what specific action, and where the action occurs. So essentially, this is saying in plain English "Any time a push is made on the main branch...run the code after it.

Now we will focus on the jobs section of the code:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm install
    // - name: Run tests
    // - run: npm test
    - name: Build file
      run: npm run build
